/**
 * Zod Validation Schemas for Server-Side API Input Validation
 *
 * Provides reusable schemas for all major entities and a `validateBody` helper
 * that returns a typed discriminated union for easy early-return in API routes.
 *
 * Usage in API routes:
 *   const result = validateBody(tripCreateSchema, body)
 *   if (!result.success) return result.response
 *   // result.data is fully typed
 */

import { z } from 'zod/v4'
import { NextResponse } from 'next/server'

// ─────────────────────────────────────────────────────────────────────────────
// Common / Reusable Schemas
// ─────────────────────────────────────────────────────────────────────────────

/** CUID v1 identifier (auto-generated by Prisma) */
export const idSchema = z.string().min(1)

/** RFC 5322–ish email validation */
export const emailSchema = z
  .string()
  .email('Invalid email address')
  .max(255, 'Email must be at most 255 characters')

/**
 * Phone number — supports Ghana (+233 / 0xxx) and international formats.
 * Accepts digits, spaces, hyphens, parentheses, and a leading +.
 */
export const phoneSchema = z
  .string()
  .min(7, 'Phone number must be at least 7 digits')
  .max(20, 'Phone number must be at most 20 characters')
  .regex(/^[+\d()\- ]+$/, 'Phone number contains invalid characters')

/** Pagination parameters commonly used across list endpoints. */
export const paginationSchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
})

// ─────────────────────────────────────────────────────────────────────────────
// Enum / Literal helpers
// ─────────────────────────────────────────────────────────────────────────────

const truckStatusEnum = z.enum(['active', 'inactive', 'maintenance', 'out_of_service'])
const truckFuelTypeEnum = z.enum(['Diesel', 'Petrol', 'CNG', 'Electric', 'Hybrid'])
const driverVerificationStatusEnum = z.enum(['pending', 'verified', 'rejected', 'expired'])
const licenseClassEnum = z.enum(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])
const paymentMethodEnum = z.enum(['cash', 'card', 'bank_transfer', 'mobile_money', 'cheque', 'other'])
const expenseCategoryEnum = z.enum([
  'fuel',
  'maintenance',
  'tolls',
  'insurance',
  'registration',
  'tyres',
  'parts',
  'parking',
  'wash',
  'towing',
  'fines',
  'salaries',
  'miscellaneous',
])
const expenseStatusEnum = z.enum(['approved', 'pending', 'rejected'])
const fuelTypeEnum = z.enum(['Diesel', 'Petrol', 'CNG', 'Electric', 'Hybrid'])
const maintenanceTypeEnum = z.enum([
  'routine',
  'repair',
  'inspection',
  'tyre_change',
  'oil_change',
  'brake_service',
  'electrical',
  'bodywork',
  'other',
])
const deliveryTypeEnum = z.enum(['single', 'multi_drop'])
const invoiceStatusEnum = z.enum(['draft', 'sent', 'paid', 'overdue', 'cancelled', 'partial'])

// ─────────────────────────────────────────────────────────────────────────────
// Entity Schemas
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Trip creation schema.
 * Mirrors the POST body of /api/trips.
 *
 * Required: truckId, driverId, departureTime
 * Note: loadingLocation and destination are effectively required but can be
 * auto-populated from loadingPointId / destinationZoneId server-side, so they
 * remain optional at the schema level to let the API handle that logic.
 */
export const tripCreateSchema = z.object({
  truckId: idSchema,
  driverId: idSchema,
  departureTime: z.coerce.date({ error: 'Invalid departure time' }),

  // Identity / reference
  waybillNumber: z.string().max(50).optional(),
  itemName: z.string().max(200).optional(),
  quantity: z.union([z.string(), z.number()]).optional(),
  unit: z.string().max(20).optional().default('bags'),
  unitPrice: z.union([z.string(), z.number()]).optional(),
  totalRevenue: z.union([z.string(), z.number()]).optional(),

  // Location
  loadingLocation: z.string().max(200).optional(),
  loadingAddress: z.string().max(300).optional(),
  destination: z.string().max(200).optional(),
  destinationAddress: z.string().max(300).optional(),

  // Zone / city / point lookups (auto-populate loadingLocation / destination)
  destinationZoneId: idSchema.optional(),
  loadingPointId: idSchema.optional(),
  loadingCityId: idSchema.optional(),
  destinationCityId: idSchema.optional(),

  // Customer info
  customerName: z.string().max(150).optional(),
  customerPhone: phoneSchema.optional(),
  customerRef: z.string().max(100).optional(),

  // Trip details
  deliveryType: deliveryTypeEnum.optional(),
  startMileage: z.union([z.string(), z.number()]).optional(),
  fuelLevelBefore: z.union([z.string(), z.number()]).optional(),
  startMileageImage: z.string().url().optional().or(z.literal('')),
  markCompleted: z.boolean().optional(),

  // Free text
  notes: z.string().max(2000).optional(),

  // Nested: trip items (multi-item trips)
  tripItems: z
    .array(
      z.object({
        supplierId: z.string().optional(),
        loadingPointId: z.string().optional(),
        itemId: z.string().optional(),
        itemName: z.string().max(200).optional(),
        unit: z.string().max(20).optional().default('bags'),
        quantity: z.union([z.string(), z.number()]).optional(),
        rate: z.union([z.string(), z.number()]).optional(),
        total: z.union([z.string(), z.number()]).optional(),
        deliveryDestinationId: z.string().optional(),
      })
    )
    .optional(),

  // Nested: delivery destinations (multi-drop)
  deliveryDestinations: z
    .array(
      z.object({
        _tempId: z.string().optional(),
        stopOrder: z.union([z.string(), z.number()]).optional(),
        sortOrder: z.union([z.string(), z.number()]).optional(),
        clientId: z.string().optional(),
        customerName: z.string().max(150).optional(),
        customerPhone: phoneSchema.optional(),
        destinationZoneId: z.string().optional(),
        zoneRate: z.union([z.string(), z.number()]).optional(),
        address: z.string().max(300).optional(),
        notes: z.string().max(1000).optional(),
        status: z.string().max(50).optional(),
        actualQty: z.union([z.string(), z.number()]).optional(),
      })
    )
    .optional(),
})

/**
 * Truck creation schema.
 * Mirrors the POST body of /api/trucks.
 *
 * Required: plateNumber, make, model, year
 */
export const truckCreateSchema = z.object({
  plateNumber: z.string().min(2, 'Plate number is required').max(20, 'Plate number too long'),
  make: z.string().min(1, 'Make is required').max(50, 'Make must be at most 50 characters'),
  model: z.string().min(1, 'Model is required').max(50, 'Model must be at most 50 characters'),
  year: z.coerce
    .number()
    .int()
    .min(1900, 'Year must be 1900 or later')
    .max(new Date().getFullYear() + 2, 'Year cannot be more than 2 years in the future'),

  vinNumber: z.string().max(50).optional(),
  engineNumber: z.string().max(50).optional(),
  chassisNumber: z.string().max(50).optional(),
  color: z.string().max(30).optional(),
  fuelType: truckFuelTypeEnum.optional().default('Diesel'),
  tankCapacity: z.coerce.number().positive().max(5000).optional(),
  status: truckStatusEnum.optional().default('active'),
  notes: z.string().max(2000).optional(),
})

/**
 * Driver creation schema.
 * Mirrors the POST body of /api/drivers.
 *
 * Required: firstName, lastName, phone, licenseNumber, licenseExpiry, licenseClass
 */
export const driverCreateSchema = z.object({
  firstName: z.string().min(1, 'First name is required').max(50),
  lastName: z.string().min(1, 'Last name is required').max(50),
  phone: phoneSchema,
  email: emailSchema.optional().or(z.literal('')),
  licenseNumber: z.string().min(1, 'License number is required').max(50),
  licenseExpiry: z.coerce.date({ error: 'Invalid license expiry date' }),
  licenseClass: licenseClassEnum,
  licenseImage: z.string().url().optional().or(z.literal('')),

  // Ghana Card
  ghanaCardNumber: z.string().max(50).optional(),
  ghanaCardExpiry: z.coerce.date({ error: 'Invalid Ghana Card expiry date' }).optional(),
  ghanaCardFrontImage: z.string().url().optional().or(z.literal('')),
  ghanaCardBackImage: z.string().url().optional().or(z.literal('')),

  // Personal
  dateOfBirth: z.coerce.date({ error: 'Invalid date of birth' }).optional(),
  address: z.string().max(300).optional(),
  photo: z.string().url().optional().or(z.literal('')),

  // Emergency contact
  emergencyName: z.string().max(100).optional(),
  emergencyPhone: phoneSchema.optional(),

  // Employment
  employeeId: z.string().max(30).optional(),
  verificationStatus: driverVerificationStatusEnum.optional().default('pending'),

  // Linked user account creation
  createAccount: z.boolean().optional().default(false),
  accountEmail: emailSchema.optional(),
  accountPassword: z.string().min(4, 'Account password must be at least 4 characters').max(128).optional(),
}).refine(
  (data) => {
    // When createAccount is true, accountEmail and accountPassword must be present
    if (data.createAccount && (!data.accountEmail || !data.accountPassword)) {
      return false
    }
    return true
  },
  {
    message: 'accountEmail and accountPassword are required when createAccount is true',
    path: ['createAccount'],
  }
)

/**
 * Expense creation schema.
 * Mirrors the POST body of /api/expenses.
 *
 * Required: truckId, category, description, amount, date
 */
export const expenseCreateSchema = z.object({
  truckId: idSchema,
  category: expenseCategoryEnum,
  description: z.string().min(1, 'Description is required').max(500),
  amount: z.union([z.string(), z.number()]),
  date: z.coerce.date({ error: 'Invalid expense date' }),

  paymentMethod: paymentMethodEnum.optional().default('cash'),
  reference: z.string().max(100).optional(),
  tripId: idSchema.optional(),
})

/**
 * Fuel log creation schema.
 * Mirrors the POST body of /api/fuel-logs.
 *
 * Required: truckId, tripId, litersFilled, totalCost, date
 */
export const fuelLogCreateSchema = z.object({
  truckId: idSchema,
  tripId: idSchema,
  date: z.coerce.date({ error: 'Invalid fuel log date' }),
  litersFilled: z.union([z.string(), z.number()]),
  totalCost: z.union([z.string(), z.number()]),

  odometer: z.union([z.string(), z.number()]).optional(),
  fuelLevelBefore: z.union([z.string(), z.number()]).optional(),
  fuelLevelAfter: z.union([z.string(), z.number()]).optional(),
  costPerLiter: z.union([z.string(), z.number()]).optional(),
  stationName: z.string().max(200).optional(),
  fuelType: fuelTypeEnum.optional().default('Diesel'),
  receiptNumber: z.string().max(100).optional(),
  endMileage: z.union([z.string(), z.number()]).optional(),
  endMileageImage: z.string().url().optional().or(z.literal('')),
  images: z.string().max(5000).optional(), // JSON array of URLs
  distanceCovered: z.union([z.string(), z.number()]).optional(),
  notes: z.string().max(2000).optional(),
})

/**
 * User creation schema.
 * Mirrors the POST body of /api/users.
 *
 * Required: name, roleId
 * When hasSystemAccess (or email is provided): email + password required
 */
export const userCreateSchema = z.object({
  name: z.string().min(1, 'Name is required').max(100),
  email: emailSchema.optional().or(z.literal('')),
  phone: phoneSchema.optional().or(z.literal('')),
  password: z.string().max(128).optional(),
  roleId: idSchema,
  isActive: z.boolean().optional().default(true),
  position: z.string().max(100).optional(),
  department: z.string().max(100).optional(),
  employeeNumber: z.string().max(30).optional(),
  hasSystemAccess: z.boolean().optional(),
}).refine(
  (data) => {
    // System access users must have email + password
    const systemAccess = data.hasSystemAccess !== undefined ? data.hasSystemAccess : !!data.email
    if (systemAccess && (!data.email || !data.password)) {
      return false
    }
    return true
  },
  {
    message: 'Email and password are required for staff with system access',
    path: ['hasSystemAccess'],
  }
).refine(
  (data) => {
    // Password must be at least 4 chars when provided
    if (data.password && data.password.length < 4) {
      return false
    }
    return true
  },
  {
    message: 'Password must be at least 4 characters',
    path: ['password'],
  }
)

/**
 * Invoice creation schema.
 * Mirrors the POST body of /api/invoices.
 *
 * Required: clientId, dueDate, items (array with at least 1 item)
 */
export const invoiceCreateSchema = z.object({
  clientId: idSchema,
  tripId: idSchema.optional(),
  issueDate: z.coerce.date({ error: 'Invalid issue date' }).optional(),
  dueDate: z.coerce.date({ error: 'Invalid due date' }),
  taxRate: z.coerce.number().min(0).max(100).optional().default(0),
  notes: z.string().max(5000).optional(),
  terms: z.string().max(5000).optional(),

  items: z
    .array(
      z.object({
        description: z.string().min(1, 'Item description is required').max(1000),
        quantity: z.number({ coerce: true }).positive('Item quantity must be positive'),
        unitPrice: z.number({ coerce: true }).nonnegative('Item unit price must be zero or more'),
        total: z.number({ coerce: true }).optional(),
        order: z.number({ coerce: true }).int().optional(),
      })
    )
    .min(1, 'At least one invoice item is required')
    .max(100, 'An invoice can have at most 100 items'),
})

/**
 * Maintenance record creation schema.
 * Mirrors the POST body of /api/maintenance.
 *
 * Required: truckId, type, title
 */
export const maintenanceCreateSchema = z.object({
  truckId: idSchema,
  type: maintenanceTypeEnum,
  title: z.string().min(1, 'Title is required').max(200),
  description: z.string().max(5000).optional(),
  odometer: z.coerce.number().nonnegative().optional(),
  cost: z.coerce.number().nonnegative().optional(),
  performedBy: z.string().max(100).optional(),
  nextDueDate: z.coerce.date({ error: 'Invalid next due date' }).optional(),
  nextDueMileage: z.coerce.number().nonnegative().optional(),
})

// ─────────────────────────────────────────────────────────────────────────────
// Query Parameter Schemas (for GET endpoints)
// ─────────────────────────────────────────────────────────────────────────────

/** Common date range filter for list endpoints. */
export const dateRangeSchema = z.object({
  dateFrom: z.string().datetime().or(z.string().date()).optional(),
  dateTo: z.string().datetime().or(z.string().date()).optional(),
})

/** Common search + pagination filter for list endpoints. */
export const listQuerySchema = z.object({
  search: z.string().max(200).optional(),
  status: z.string().max(50).optional(),
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
})

// ─────────────────────────────────────────────────────────────────────────────
// Helper Functions
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Validate a request body against a Zod schema.
 *
 * Returns a discriminated union:
 *   - `{ success: true; data: T }`       — validation passed, `data` is fully typed
 *   - `{ success: false; response }`       — validation failed, `response` is a 400 NextResponse
 *
 * @example
 *   const result = validateBody(tripCreateSchema, await request.json())
 *   if (!result.success) return result.response
 *   const { truckId, driverId, departureTime } = result.data
 */
export function validateBody<T>(
  schema: z.ZodType<T>,
  body: unknown
): { success: true; data: T } | { success: false; response: NextResponse } {
  const result = schema.safeParse(body)
  if (!result.success) {
    const errors = result.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`)
    return {
      success: false,
      response: NextResponse.json(
        { error: 'Validation failed', details: errors },
        { status: 400 }
      ),
    }
  }
  return { success: true, data: result.data }
}

/**
 * Validate query parameters against a Zod schema.
 * Accepts a URLSearchParams or plain object and returns the same
 * discriminated union as `validateBody`.
 */
export function validateQuery<T>(
  schema: z.ZodType<T>,
  params: URLSearchParams | Record<string, string | string[] | undefined>
): { success: true; data: T } | { success: false; response: NextResponse } {
  const obj: Record<string, unknown> = {}
  if (params instanceof URLSearchParams) {
    params.forEach((value, key) => {
      obj[key] = value
    })
  } else {
    for (const [key, value] of Object.entries(params)) {
      if (value !== undefined) {
        obj[key] = Array.isArray(value) ? value[0] : value
      }
    }
  }
  return validateBody(schema, obj)
}
