import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'

export async function POST() {
  try {
    // Seed Warehouses
    const warehouses = await Promise.all([
      db.warehouse.create({
        data: {
          name: 'Accra Main Depot',
          code: 'ACC-01',
          address: '23 Industrial Area, Ring Road Central',
          city: 'Accra',
          region: 'Greater Accra',
          contactPerson: 'Kwame Asante',
          contactPhone: '+233-24-555-1001',
        },
      }),
      db.warehouse.create({
        data: {
          name: 'Tema Port Warehouse',
          code: 'TEM-01',
          address: 'Tema Harbour Road, Industrial Area',
          city: 'Tema',
          region: 'Greater Accra',
          contactPerson: 'Ama Mensah',
          contactPhone: '+233-20-555-2001',
        },
      }),
      db.warehouse.create({
        data: {
          name: 'Kumasi Hub',
          code: 'KUM-01',
          address: '45 Suame Magazine Road',
          city: 'Kumasi',
          region: 'Ashanti',
          contactPerson: 'Kofi Boateng',
          contactPhone: '+233-27-555-3001',
        },
      }),
      db.warehouse.create({
        data: {
          name: 'Takoradi Storage',
          code: 'TAK-01',
          address: '12 Takoradi Port Road',
          city: 'Takoradi',
          region: 'Western',
          contactPerson: 'Abena Darko',
          contactPhone: '+233-28-555-4001',
        },
      }),
    ])

    // Seed Zone Rates
    const zoneRates = await Promise.all([
      db.zoneRate.create({
        data: {
          zoneName: 'Accra-Tema Corridor',
          fromRegion: 'Greater Accra',
          toRegion: 'Greater Accra',
          ratePerKm: 3.5,
          minimumRate: 150,
          waitingRate: 25,
        },
      }),
      db.zoneRate.create({
        data: {
          zoneName: 'Accra-Kumasi Route',
          fromRegion: 'Greater Accra',
          toRegion: 'Ashanti',
          ratePerKm: 5.0,
          minimumRate: 500,
          waitingRate: 35,
        },
      }),
      db.zoneRate.create({
        data: {
          zoneName: 'Accra-Takoradi Route',
          fromRegion: 'Greater Accra',
          toRegion: 'Western',
          ratePerKm: 4.8,
          minimumRate: 450,
          waitingRate: 30,
        },
      }),
      db.zoneRate.create({
        data: {
          zoneName: 'Kumasi-Takoradi Route',
          fromRegion: 'Ashanti',
          toRegion: 'Western',
          ratePerKm: 5.5,
          minimumRate: 400,
          waitingRate: 30,
        },
      }),
      db.zoneRate.create({
        data: {
          zoneName: 'Accra-Tamale Route',
          fromRegion: 'Greater Accra',
          toRegion: 'Northern',
          ratePerKm: 6.0,
          minimumRate: 800,
          waitingRate: 40,
        },
      }),
      db.zoneRate.create({
        data: {
          zoneName: 'Kumasi-Tamale Route',
          fromRegion: 'Ashanti',
          toRegion: 'Northern',
          ratePerKm: 5.2,
          minimumRate: 600,
          waitingRate: 35,
        },
      }),
    ])

    // Seed Drivers
    const drivers = await Promise.all([
      db.driver.create({
        data: {
          driverName: 'Emmanuel Owusu',
          phone: '+233-24-123-4567',
          licenseNo: 'DVR-GH-2021-00123',
          licenseExpiry: new Date('2026-03-15'),
          emergencyContact: 'Grace Owusu',
          emergencyPhone: '+233-20-123-4567',
          address: '12 Dansoman, Accra',
          status: 'active',
          hireDate: new Date('2021-06-01'),
        },
      }),
      db.driver.create({
        data: {
          driverName: 'Joseph Amponsah',
          phone: '+233-27-234-5678',
          licenseNo: 'DVR-GH-2020-00456',
          licenseExpiry: new Date('2025-09-20'),
          emergencyContact: 'Mary Amponsah',
          emergencyPhone: '+233-24-234-5678',
          address: '45 Suame, Kumasi',
          status: 'active',
          hireDate: new Date('2020-01-15'),
        },
      }),
      db.driver.create({
        data: {
          driverName: 'Samuel Tetteh',
          phone: '+233-20-345-6789',
          licenseNo: 'DVR-GH-2022-00789',
          licenseExpiry: new Date('2027-01-10'),
          emergencyContact: 'Adelaide Tetteh',
          emergencyPhone: '+233-27-345-6789',
          address: '8 Tema Community 12',
          status: 'active',
          hireDate: new Date('2022-03-20'),
        },
      }),
      db.driver.create({
        data: {
          driverName: 'Daniel Adjei',
          phone: '+233-28-456-7890',
          licenseNo: 'DVR-GH-2019-00112',
          licenseExpiry: new Date('2025-06-30'),
          emergencyContact: 'Beatrice Adjei',
          emergencyPhone: '+233-20-456-7890',
          address: '34 Takoradi Anaji',
          status: 'active',
          hireDate: new Date('2019-11-05'),
        },
      }),
    ])

    // Seed Trucks
    const trucks = await Promise.all([
      db.truck.create({
        data: {
          plateNumber: 'GR-1234-A',
          truckName: 'Hino Ranger',
          truckType: 'flatbed',
          capacity: '20 tons',
          year: 2021,
          fuelType: 'diesel',
          status: 'active',
          mileage: 85000,
          lastService: new Date('2025-01-10'),
          insuranceExpiry: new Date('2026-01-10'),
        },
      }),
      db.truck.create({
        data: {
          plateNumber: 'AW-5678-B',
          truckName: 'Volvo FH16',
          truckType: 'flatbed',
          capacity: '30 tons',
          year: 2020,
          fuelType: 'diesel',
          status: 'active',
          mileage: 120000,
          lastService: new Date('2024-12-15'),
          insuranceExpiry: new Date('2025-12-15'),
        },
      }),
      db.truck.create({
        data: {
          plateNumber: 'AS-9012-C',
          truckName: 'MAN TGX',
          truckType: 'container',
          capacity: '25 tons',
          year: 2022,
          fuelType: 'diesel',
          status: 'active',
          mileage: 45000,
          lastService: new Date('2025-02-01'),
          insuranceExpiry: new Date('2026-06-01'),
        },
      }),
      db.truck.create({
        data: {
          plateNumber: 'GN-3456-D',
          truckName: 'Scania R450',
          truckType: 'tanker',
          capacity: '18000 liters',
          year: 2021,
          fuelType: 'diesel',
          status: 'active',
          mileage: 95000,
          lastService: new Date('2025-01-20'),
          insuranceExpiry: new Date('2025-11-20'),
        },
      }),
      db.truck.create({
        data: {
          plateNumber: 'NR-7890-E',
          truckName: 'Isuzu FTR',
          truckType: 'refrigerated',
          capacity: '10 tons',
          year: 2023,
          fuelType: 'diesel',
          status: 'active',
          mileage: 20000,
          lastService: new Date('2025-03-01'),
          insuranceExpiry: new Date('2027-03-01'),
        },
      }),
      db.truck.create({
        data: {
          plateNumber: 'UE-2345-F',
          truckName: 'DAF XF',
          truckType: 'flatbed',
          capacity: '28 tons',
          year: 2019,
          fuelType: 'diesel',
          status: 'maintenance',
          mileage: 180000,
          lastService: new Date('2025-02-15'),
          insuranceExpiry: new Date('2025-08-15'),
        },
      }),
    ])

    // Generate trip numbers
    const today = new Date()
    const dateStr =
      today.getFullYear().toString() +
      String(today.getMonth() + 1).padStart(2, '0') +
      String(today.getDate()).padStart(2, '0')

    const tripData = [
      {
        tripNumber: `TRP-${dateStr}-001`,
        driverId: drivers[0].id,
        truckId: trucks[0].id,
        fromWarehouseId: warehouses[0].id,
        toWarehouseId: warehouses[1].id,
        status: 'completed',
        departureDate: new Date('2025-06-01T06:00:00'),
        arrivalDate: new Date('2025-06-01T08:30:00'),
        originAddress: 'Accra Main Depot',
        destinationAddress: 'Tema Port Warehouse',
        distance: 30,
        fuelUsed: 45,
        baseRate: 150,
        waitingCharges: 50,
        otherCharges: 20,
        cargoDescription: 'Building materials',
        cargoWeight: 18,
      },
      {
        tripNumber: `TRP-${dateStr}-002`,
        driverId: drivers[1].id,
        truckId: trucks[1].id,
        fromWarehouseId: warehouses[0].id,
        toWarehouseId: warehouses[2].id,
        status: 'completed',
        departureDate: new Date('2025-06-03T05:00:00'),
        arrivalDate: new Date('2025-06-03T12:00:00'),
        originAddress: 'Accra Main Depot',
        destinationAddress: 'Kumasi Hub',
        distance: 270,
        fuelUsed: 340,
        baseRate: 1350,
        waitingCharges: 100,
        otherCharges: 0,
        cargoDescription: 'Electronics',
        cargoWeight: 25,
      },
      {
        tripNumber: `TRP-${dateStr}-003`,
        driverId: drivers[2].id,
        truckId: trucks[2].id,
        fromWarehouseId: warehouses[1].id,
        toWarehouseId: warehouses[3].id,
        status: 'completed',
        departureDate: new Date('2025-06-05T07:00:00'),
        arrivalDate: new Date('2025-06-05T14:00:00'),
        originAddress: 'Tema Port Warehouse',
        destinationAddress: 'Takoradi Storage',
        distance: 220,
        fuelUsed: 280,
        baseRate: 1056,
        waitingCharges: 75,
        otherCharges: 30,
        cargoDescription: 'Container goods',
        cargoWeight: 22,
      },
      {
        tripNumber: `TRP-${dateStr}-004`,
        driverId: drivers[3].id,
        truckId: trucks[3].id,
        fromWarehouseId: warehouses[2].id,
        toWarehouseId: warehouses[0].id,
        status: 'completed',
        departureDate: new Date('2025-06-08T04:30:00'),
        arrivalDate: new Date('2025-06-08T11:30:00'),
        originAddress: 'Kumasi Hub',
        destinationAddress: 'Accra Main Depot',
        distance: 270,
        fuelUsed: 330,
        baseRate: 1350,
        waitingCharges: 0,
        otherCharges: 50,
        cargoDescription: 'Cocoa beans',
        cargoWeight: 28,
      },
      {
        tripNumber: `TRP-${dateStr}-005`,
        driverId: drivers[0].id,
        truckId: trucks[4].id,
        fromWarehouseId: warehouses[0].id,
        toWarehouseId: warehouses[2].id,
        status: 'in_progress',
        departureDate: new Date('2025-06-10T06:00:00'),
        originAddress: 'Accra Main Depot',
        destinationAddress: 'Kumasi Hub',
        distance: 270,
        fuelUsed: 0,
        baseRate: 1350,
        waitingCharges: 0,
        otherCharges: 0,
        cargoDescription: 'Perishable food items',
        cargoWeight: 8,
      },
      {
        tripNumber: `TRP-${dateStr}-006`,
        driverId: drivers[1].id,
        truckId: trucks[0].id,
        fromWarehouseId: warehouses[2].id,
        toWarehouseId: warehouses[3].id,
        status: 'in_progress',
        departureDate: new Date('2025-06-11T05:30:00'),
        originAddress: 'Kumasi Hub',
        destinationAddress: 'Takoradi Storage',
        distance: 210,
        fuelUsed: 0,
        baseRate: 1155,
        waitingCharges: 0,
        otherCharges: 0,
        cargoDescription: 'Timber products',
        cargoWeight: 18,
      },
      {
        tripNumber: `TRP-${dateStr}-007`,
        driverId: drivers[2].id,
        truckId: trucks[1].id,
        fromWarehouseId: warehouses[1].id,
        toWarehouseId: warehouses[0].id,
        status: 'in_progress',
        departureDate: new Date('2025-06-12T07:00:00'),
        originAddress: 'Tema Port Warehouse',
        destinationAddress: 'Accra Main Depot',
        distance: 30,
        fuelUsed: 0,
        baseRate: 150,
        waitingCharges: 25,
        otherCharges: 0,
        cargoDescription: 'Imported goods',
        cargoWeight: 28,
      },
      {
        tripNumber: `TRP-${dateStr}-008`,
        driverId: drivers[3].id,
        truckId: trucks[2].id,
        fromWarehouseId: warehouses[0].id,
        toWarehouseId: warehouses[3].id,
        status: 'pending',
        departureDate: null,
        originAddress: 'Accra Main Depot',
        destinationAddress: 'Takoradi Storage',
        distance: 230,
        fuelUsed: 0,
        baseRate: 1104,
        waitingCharges: 0,
        otherCharges: 0,
        cargoDescription: 'Construction equipment',
        cargoWeight: 22,
      },
      {
        tripNumber: `TRP-${dateStr}-009`,
        driverId: drivers[0].id,
        truckId: trucks[3].id,
        fromWarehouseId: warehouses[3].id,
        toWarehouseId: warehouses[2].id,
        status: 'pending',
        departureDate: null,
        originAddress: 'Takoradi Storage',
        destinationAddress: 'Kumasi Hub',
        distance: 210,
        fuelUsed: 0,
        baseRate: 1155,
        waitingCharges: 0,
        otherCharges: 0,
        cargoDescription: 'Mineral products',
        cargoWeight: 24,
      },
      {
        tripNumber: `TRP-${dateStr}-010`,
        driverId: drivers[1].id,
        truckId: trucks[4].id,
        fromWarehouseId: warehouses[2].id,
        toWarehouseId: warehouses[0].id,
        status: 'pending',
        departureDate: null,
        originAddress: 'Kumasi Hub',
        destinationAddress: 'Accra Main Depot',
        distance: 270,
        fuelUsed: 0,
        baseRate: 1350,
        waitingCharges: 0,
        otherCharges: 0,
        cargoDescription: 'Fresh produce',
        cargoWeight: 9,
      },
      {
        tripNumber: `TRP-${dateStr}-011`,
        driverId: drivers[2].id,
        truckId: trucks[0].id,
        fromWarehouseId: warehouses[0].id,
        toWarehouseId: warehouses[1].id,
        status: 'completed',
        departureDate: new Date('2025-05-20T06:30:00'),
        arrivalDate: new Date('2025-05-20T09:00:00'),
        originAddress: 'Accra Main Depot',
        destinationAddress: 'Tema Port Warehouse',
        distance: 30,
        fuelUsed: 42,
        baseRate: 150,
        waitingCharges: 50,
        otherCharges: 0,
        cargoDescription: 'Textiles',
        cargoWeight: 15,
      },
      {
        tripNumber: `TRP-${dateStr}-012`,
        driverId: drivers[3].id,
        truckId: trucks[1].id,
        fromWarehouseId: warehouses[1].id,
        toWarehouseId: warehouses[2].id,
        status: 'completed',
        departureDate: new Date('2025-05-22T05:00:00'),
        arrivalDate: new Date('2025-05-22T12:30:00'),
        originAddress: 'Tema Port Warehouse',
        destinationAddress: 'Kumasi Hub',
        distance: 270,
        fuelUsed: 350,
        baseRate: 1350,
        waitingCharges: 100,
        otherCharges: 25,
        cargoDescription: 'Auto parts',
        cargoWeight: 26,
      },
      {
        tripNumber: `TRP-${dateStr}-013`,
        driverId: drivers[0].id,
        truckId: trucks[1].id,
        fromWarehouseId: warehouses[3].id,
        toWarehouseId: warehouses[0].id,
        status: 'cancelled',
        departureDate: null,
        originAddress: 'Takoradi Storage',
        destinationAddress: 'Accra Main Depot',
        distance: 230,
        fuelUsed: 0,
        baseRate: 0,
        waitingCharges: 0,
        otherCharges: 0,
        cargoDescription: 'Chemical supplies',
        cargoWeight: 20,
      },
      {
        tripNumber: `TRP-${dateStr}-014`,
        driverId: drivers[1].id,
        truckId: trucks[3].id,
        fromWarehouseId: warehouses[0].id,
        toWarehouseId: warehouses[2].id,
        status: 'completed',
        departureDate: new Date('2025-05-28T04:00:00'),
        arrivalDate: new Date('2025-05-28T11:00:00'),
        originAddress: 'Accra Main Depot',
        destinationAddress: 'Kumasi Hub',
        distance: 270,
        fuelUsed: 345,
        baseRate: 1350,
        waitingCharges: 75,
        otherCharges: 0,
        cargoDescription: 'Petroleum products',
        cargoWeight: 16,
      },
      {
        tripNumber: `TRP-${dateStr}-015`,
        driverId: drivers[2].id,
        truckId: trucks[2].id,
        fromWarehouseId: warehouses[2].id,
        toWarehouseId: warehouses[1].id,
        status: 'completed',
        departureDate: new Date('2025-05-30T06:00:00'),
        arrivalDate: new Date('2025-05-30T13:00:00'),
        originAddress: 'Kumasi Hub',
        destinationAddress: 'Tema Port Warehouse',
        distance: 270,
        fuelUsed: 335,
        baseRate: 1350,
        waitingCharges: 50,
        otherCharges: 40,
        cargoDescription: 'Shea butter exports',
        cargoWeight: 23,
      },
      {
        tripNumber: `TRP-${dateStr}-016`,
        driverId: drivers[3].id,
        truckId: trucks[0].id,
        fromWarehouseId: warehouses[0].id,
        toWarehouseId: warehouses[1].id,
        status: 'completed',
        departureDate: new Date('2025-06-02T07:00:00'),
        arrivalDate: new Date('2025-06-02T09:15:00'),
        originAddress: 'Accra Main Depot',
        destinationAddress: 'Tema Port Warehouse',
        distance: 30,
        fuelUsed: 40,
        baseRate: 150,
        waitingCharges: 25,
        otherCharges: 0,
        cargoDescription: 'Office furniture',
        cargoWeight: 12,
      },
    ]

    // Create trips with calculated totalAmount
    const trips = await Promise.all(
      tripData.map((trip) =>
        db.trip.create({
          data: {
            ...trip,
            totalAmount: trip.baseRate + trip.waitingCharges + trip.otherCharges,
          },
        })
      )
    )

    // Seed Cash Advances for drivers
    const completedTrips = trips.filter((t) => t.status === 'completed')
    await Promise.all([
      db.cashAdvance.create({
        data: {
          driverId: drivers[0].id,
          amount: 200,
          purpose: 'Fuel for Accra-Tema trip',
          tripId: completedTrips[0]?.id,
          status: 'settled',
          approvedBy: 'admin',
          approvedAt: new Date('2025-05-31T08:00:00'),
          disbursedAt: new Date('2025-06-01T05:00:00'),
          settledAt: new Date('2025-06-02T10:00:00'),
        },
      }),
      db.cashAdvance.create({
        data: {
          driverId: drivers[1].id,
          amount: 500,
          purpose: 'Fuel and tolls for Accra-Kumasi',
          tripId: completedTrips[1]?.id,
          status: 'settled',
          approvedBy: 'admin',
          approvedAt: new Date('2025-06-02T08:00:00'),
          disbursedAt: new Date('2025-06-03T04:00:00'),
          settledAt: new Date('2025-06-04T09:00:00'),
        },
      }),
      db.cashAdvance.create({
        data: {
          driverId: drivers[2].id,
          amount: 400,
          purpose: 'Fuel for Tema-Takoradi route',
          tripId: completedTrips[2]?.id,
          status: 'disbursed',
          approvedBy: 'admin',
          approvedAt: new Date('2025-06-04T08:00:00'),
          disbursedAt: new Date('2025-06-05T06:00:00'),
        },
      }),
      db.cashAdvance.create({
        data: {
          driverId: drivers[3].id,
          amount: 350,
          purpose: 'Fuel for Kumasi-Accra return',
          tripId: completedTrips[3]?.id,
          status: 'approved',
          approvedBy: 'admin',
          approvedAt: new Date('2025-06-07T08:00:00'),
        },
      }),
      db.cashAdvance.create({
        data: {
          driverId: drivers[0].id,
          amount: 150,
          purpose: 'Food and minor repairs',
          tripId: null,
          status: 'pending',
        },
      }),
    ])

    // Seed Incentives
    await Promise.all([
      db.driverIncentive.create({
        data: {
          driverId: drivers[0].id,
          tripId: completedTrips[0]?.id,
          incentiveType: 'performance',
          amount: 100,
          description: 'On-time delivery bonus - Accra to Tema',
          period: '2025-06',
          status: 'paid',
          approvedBy: 'admin',
          approvedAt: new Date('2025-06-05T08:00:00'),
          paidAt: new Date('2025-06-10T08:00:00'),
        },
      }),
      db.driverIncentive.create({
        data: {
          driverId: drivers[1].id,
          tripId: completedTrips[1]?.id,
          incentiveType: 'safety',
          amount: 150,
          description: 'Zero incident record - Accra to Kumasi',
          period: '2025-06',
          status: 'approved',
          approvedBy: 'admin',
          approvedAt: new Date('2025-06-06T08:00:00'),
        },
      }),
      db.driverIncentive.create({
        data: {
          driverId: drivers[3].id,
          tripId: completedTrips[3]?.id,
          incentiveType: 'performance',
          amount: 200,
          description: 'Extra trip completion bonus',
          period: '2025-06',
          status: 'paid',
          approvedBy: 'admin',
          approvedAt: new Date('2025-06-10T08:00:00'),
          paidAt: new Date('2025-06-12T08:00:00'),
        },
      }),
      db.driverIncentive.create({
        data: {
          driverId: drivers[2].id,
          incentiveType: 'overtime',
          amount: 120,
          description: 'Overtime payment for long haul',
          period: '2025-06',
          status: 'pending',
        },
      }),
    ])

    return NextResponse.json(
      {
        message: 'Database seeded successfully',
        data: {
          warehouses: warehouses.length,
          zoneRates: zoneRates.length,
          drivers: drivers.length,
          trucks: trucks.length,
          trips: trips.length,
        },
      },
      { status: 201 }
    )
  } catch (error) {
    console.error('Seed error:', error)
    return NextResponse.json(
      { error: 'Failed to seed database', details: String(error) },
      { status: 500 }
    )
  }
}
